### ISSUE TITLE
graphics.splash not found

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_CircuitPython_Qualia#1]
Hi @makermelissa 👋 
Was just about to run some of these examples, and the one I wanted has mention of this graphics.splash displaygroup that isn't defined.
https://github.com/adafruit/Adafruit_CircuitPython_Qualia/blob/main/examples/qualia_paint.py#L32

Thanks for your work on this!

**Comment by makermelissa** [comment]
Ok thanks. I’ll have to test again. Possibly my PortalBase might have been a little modified. You're welcome.

**Comment by makermelissa** [comment]
I have been unable to produce this issue. I used a fresh copy of PortalBase, a fresh copy of the Qualia lib and ran the code as the example is written, changing only the display type.

**Comment by makermelissa** [comment]
I also tried the latest CircuitPython, but due to a bug (https://github.com/adafruit/circuitpython/issues/8574), I had to add a couple things to my settings.toml to run on there.

**Comment by tyeth** [comment]
My bad, I forgot this relied on portalbase, I was trying to navigate the code using the symbols section on GitHub code view and couldn't find mention of splash or splash group anywhere
