### ISSUE TITLE
flicker on 4.0 inch 720x720

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_Qualia#4]
I am running the examples from:
https://learn.adafruit.com/simplifying-qualia-cirtcuitpython-projects/code-examples
on a 4.0 inch 720x720 inch screen.  https://www.adafruit.com/product/5795
They are working OK, but I am getting a lot of flicker. I this a known issue or is there something I should try tweaking?

**Comment by jerryneedell** [comment]
This appears to be a known issue 

https://forums.adafruit.com/viewtopic.php?t=205181&hilit=Qualia

Is it useful to have this as an issue here? If not, please close.

**Comment by makermelissa** [comment]
Closing since this is hardware related and not an issue with the library.

**Comment by jerryneedell** [comment]
@makermelissa Thanks!  So I think you are confirming that there is an issue with flicker, jut not with the library.  Any hope for a fix?

**Comment by makermelissa** [comment]
I think it also happens on Arduino. You can try running the rainbow demo in the guide and see if it still flickers as much.

**Comment by jerryneedell** [comment]
I did -- it is worse ;-)
